# Generated by Django 3.2 on 2022-11-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='tax_brl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='broker',
            name='tax_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='broker',
            name='tax_usd',
            field=models.FloatField(default=0.0),
        ),
    ]
