# Generated by Django 3.2 on 2023-01-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_auto_20221104_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='main_currency',
            field=models.CharField(default='BRL', max_length=3),
        ),
    ]
