# Generated by Django 3.2 on 2023-02-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_broker_main_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='main_currency',
            field=models.CharField(choices=[('BRL', 'BRL'), ('USD', 'USD'), ('EUR', 'EUR')], default='BRL', max_length=3),
        ),
    ]
