# Generated by Django 3.2 on 2023-06-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0004_alter_broker_main_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='main_currency',
        ),
    ]
