# Generated by Django 3.2 on 2023-07-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0008_currencyhistoricalprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyHistoricalPrice',
        ),
    ]
