# Generated by Django 3.2 on 2023-07-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('brokers', '0009_delete_currencyhistoricalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='main_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.currency'),
        ),
    ]
