# Generated by Django 3.2 on 2023-07-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0010_alter_broker_main_currency'),
        ('investments', '0048_alter_currencyholding_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
