# Generated by Django 3.2 on 2022-02-02 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20220201_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioasset',
            name='broker',
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='total_cost_brl',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='total_today_brl',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=18),
        ),
    ]
