# Generated by Django 3.2 on 2022-02-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20220202_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('share_cost_brl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_cost_brl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('order', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=8)),
                ('portfolio_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioasset')),
            ],
            options={
                'verbose_name_plural': '  Transactions',
            },
        ),
    ]
