# Generated by Django 3.2 on 2022-02-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='new_average_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_cost_brl',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=18),
        ),
    ]
