# Generated by Django 3.2 on 2022-02-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20220208_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='broker_asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.brokerasset'),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='shares_amount',
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='portfolio_asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioasset'),
        ),
    ]
