# Generated by Django 3.2 on 2022-02-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_auto_20220208_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='broker_average_price',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brokerasset',
            name='shares_amount',
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shares_amount',
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
    ]
