# Generated by Django 3.2 on 2022-02-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_auto_20220208_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='portfolio_asset',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioasset'),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='shares_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
    ]
