# Generated by Django 3.2 on 2022-02-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_auto_20220209_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='new_average_price',
            new_name='portfolio_avarage_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.broker'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='broker_asset',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='portfolios.brokerasset'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='broker_average_price',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=18),
            preserve_default=False,
        ),
    ]
