# Generated by Django 3.2 on 2022-02-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_auto_20220209_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerasset',
            name='share_average_price_brl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='brokerasset',
            name='shares_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='brokerasset',
            name='total_cost_brl',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='brokerasset',
            name='total_today_brl',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='share_average_price_brl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='total_cost_brl',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='total_today_brl',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='broker_average_price',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='portfolio_avarage_price',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='share_cost_brl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shares_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_cost_brl',
            field=models.FloatField(editable=False),
        ),
    ]
