# Generated by Django 3.2 on 2022-02-11 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_auto_20220210_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('total_today_brl', models.FloatField()),
                ('order_value', models.FloatField()),
                ('tokens_amount', models.FloatField()),
                ('token_price', models.FloatField()),
                ('month_profit', models.FloatField()),
                ('year_profit', models.FloatField()),
                ('portfolio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'verbose_name_plural': '  Portfolio tokens',
            },
        ),
    ]
