# Generated by Django 3.2 on 2022-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0014_portfoliotoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliotoken',
            name='month_profit',
        ),
        migrations.RemoveField(
            model_name='portfoliotoken',
            name='year_profit',
        ),
        migrations.AddField(
            model_name='portfoliotoken',
            name='historical_average_price',
            field=models.FloatField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='portfoliotoken',
            name='historical_profit',
            field=models.FloatField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliotoken',
            name='profit',
            field=models.FloatField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='portfoliotoken',
            name='token_price',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='portfoliotoken',
            name='tokens_amount',
            field=models.FloatField(editable=False),
        ),
    ]
