# Generated by Django 3.2 on 2022-02-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0017_alter_portfoliotoken_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
