# Generated by Django 3.2 on 2022-02-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0018_alter_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliotoken',
            name='transaction',
        ),
    ]
