# Generated by Django 3.2 on 2022-02-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0019_remove_portfoliotoken_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioasset',
            options={'verbose_name_plural': '  Assets per portfolio'},
        ),
        migrations.AlterModelOptions(
            name='portfoliotoken',
            options={'verbose_name_plural': '  Tokens per Porftolio'},
        ),
    ]
