# Generated by Django 3.2 on 2022-02-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0020_auto_20220215_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioasset',
            name='dividends_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='trade_profit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='share_average_price_brl',
            field=models.FloatField(default=0),
        ),
    ]
