# Generated by Django 3.2 on 2022-04-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('portfolios', '0021_auto_20220220_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerasset',
            options={'verbose_name_plural': '  Portfolio Assets (per Broker)'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': '     Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='portfolioasset',
            options={'verbose_name_plural': '   Portfolio Assets'},
        ),
        migrations.AlterModelOptions(
            name='portfoliotoken',
            options={'verbose_name_plural': ' Porftolio Tokens'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': '    Portfolio Transactions'},
        ),
        migrations.AlterField(
            model_name='brokerasset',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brokers.broker'),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='trade_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brokers.broker'),
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
    ]
