# Generated by Django 3.2 on 2022-05-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('portfolios', '0022_auto_20220426_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioasset',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brokers.broker'),
        ),
    ]
