# Generated by Django 3.2 on 2022-05-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0023_portfolioasset_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='broker_asset',
        ),
        migrations.DeleteModel(
            name='BrokerAsset',
        ),
    ]
