# Generated by Django 3.2 on 2022-09-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0026_transaction_profit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': ' Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='portfolioasset',
            options={'verbose_name_plural': '  Investimentos do Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='portfoliotoken',
            options={'verbose_name_plural': 'Evolução do Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': ' Transações'},
        ),
    ]
