# Generated by Django 3.2 on 2022-09-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0001_initial'),
        ('portfolios', '0027_auto_20220926_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDividends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dividends.dividend')),
                ('portfolio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Dividendos',
            },
        ),
    ]
