# Generated by Django 3.2 on 2022-09-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0029_rename_portfoliodividends_portfoliodividend'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodividend',
            name='portfolio_asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioasset'),
        ),
    ]
