# Generated by Django 3.2 on 2022-09-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0030_portfoliodividend_portfolio_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioasset',
            options={'verbose_name_plural': '  Investimentos por Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='portfoliodividend',
            options={'verbose_name_plural': 'Dividendos por Portfolio'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='portfolio_avarage_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='profit',
        ),
    ]
