# Generated by Django 3.2 on 2022-09-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0031_auto_20220928_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioasset',
            name='share_average_price_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='total_cost_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='total_today_usd',
            field=models.FloatField(default=0),
        ),
    ]
