# Generated by Django 3.2 on 2022-09-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0032_auto_20220930_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotoken',
            name='total_today_usd',
            field=models.FloatField(default=0),
        ),
    ]
