# Generated by Django 3.2 on 2022-10-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0033_portfoliotoken_total_today_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodividend',
            name='average_price_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='average_price_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='record_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='shares_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='total_dividend_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='total_dividend_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='value_per_share_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='value_per_share_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='yield_on_cost',
            field=models.FloatField(default=0),
        ),
    ]
