# Generated by Django 3.2 on 2022-10-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0035_auto_20221004_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodividend',
            name='ticker',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
