# Generated by Django 3.2 on 2022-10-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0036_portfoliodividend_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodividend',
            name='category',
            field=models.CharField(choices=[('Ação', 'BrStocks'), ('FII', 'Fii'), ('ETF', 'ETF'), ('Stocks', 'Stocks'), ('Reits', 'Reits'), ('PrivateAsset', 'PrivateAsset')], default='Ação', max_length=100),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='dividend_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='subcategory',
            field=models.CharField(choices=[('R', 'Dividendo'), ('J', 'JCP')], default='R', max_length=10),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='usd_on_pay_date',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfoliodividend',
            name='portfolio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
    ]
