# Generated by Django 3.2 on 2022-10-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0037_auto_20221005_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioasset',
            old_name='dividends_profit',
            new_name='dividends_profit_brl',
        ),
        migrations.RenameField(
            model_name='portfolioasset',
            old_name='trade_profit',
            new_name='trade_profit_brl',
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='dividends_profit_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='trade_profit_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfoliodividend',
            name='category',
            field=models.CharField(choices=[('Ação', 'BrStocks'), ('FII', 'Fii'), ('ETF', 'ETF'), ('Stocks', 'Stocks'), ('Reit', 'Reit'), ('PrivateAsset', 'PrivateAsset')], default='Ação', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfoliodividend',
            name='subcategory',
            field=models.CharField(choices=[('R', 'Rendimentos'), ('J', 'JCP'), ('D', 'Dividendos'), ('A', 'Aluguel')], default='R', max_length=10),
        ),
    ]
