# Generated by Django 3.2 on 2022-10-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0038_auto_20221007_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioasset',
            name='total_cost_usd',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='total_today_usd',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='portfoliodividend',
            name='category',
            field=models.CharField(choices=[('Ação', 'Ações Brasileiras'), ('FII', 'Fundos Imobiliários'), ('ETF', 'ETFs'), ('Stocks', 'Stocks'), ('Reit', 'REITs'), ('PrivateAsset', 'Ativos Privados')], default='Ação', max_length=100),
        ),
    ]
