# Generated by Django 3.2 on 2022-10-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0034_remove_asset_price'),
        ('brokers', '0001_initial'),
        ('portfolios', '0039_auto_20221017_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='PortfolioTrade',
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='dividends_profit_brl',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='dividends_profit_usd',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='trade_profit_brl',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='trade_profit_usd',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
