# Generated by Django 3.2 on 2022-10-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('investments', '0034_remove_asset_price'),
        ('portfolios', '0041_auto_20221019_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioAsset',
            new_name='PortfolioInvestment',
        ),
    ]
