# Generated by Django 3.2 on 2022-10-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0042_rename_portfolioasset_portfolioinvestment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliotrade',
            name='portfolio_asset',
        ),
        migrations.AddField(
            model_name='portfoliotrade',
            name='share_cost_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliotrade',
            name='tax_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliotrade',
            name='tax_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliotrade',
            name='total_cost_usd',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='portfoliotrade',
            name='asset',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='portfoliotrade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfoliotrade',
            name='order',
            field=models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], default='C', max_length=8),
        ),
        migrations.AlterField(
            model_name='portfoliotrade',
            name='share_cost_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfoliotrade',
            name='shares_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfoliotrade',
            name='total_cost_brl',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
