# Generated by Django 3.2 on 2022-10-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0043_auto_20221019_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotrade',
            name='category',
            field=models.CharField(choices=[('Criptomoeda', 'Criptomoeda'), ('Ação', 'Ação'), ('FII', 'FII'), ('Stock', 'Stock')], default='Ação', max_length=15),
        ),
        migrations.AddField(
            model_name='portfoliotrade',
            name='usd_on_date',
            field=models.FloatField(default=0),
        ),
    ]
