# Generated by Django 3.2 on 2022-10-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0044_auto_20221025_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='total_today_usd',
            new_name='share_cost_brl',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='historical_average_price',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='historical_profit',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='order_value',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='token_price',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='tokens_amount',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='total_today_brl',
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='asset',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='order',
            field=models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], default='C', max_length=8),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='share_average_price_brl',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='share_average_price_usd',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='share_cost_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='shares_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='tax_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='tax_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='total_cost_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='total_cost_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='trade_profit_brl',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='trade_profit_usd',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='portfoliotrade',
            name='category',
            field=models.CharField(choices=[('Criptomoeda', 'Criptomoeda'), ('Ação', 'Ação'), ('FII', 'FII'), ('Stock', 'Stock'), ('REIT', 'REIT'), ('ETF', 'ETF'), ('Currency', 'Currency')], default='Ação', max_length=15),
        ),
    ]
