# Generated by Django 3.2 on 2022-10-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0046_portfoliohistory_total_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='share_cost_brl',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='share_cost_usd',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='shares_amount',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='tax_brl',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='tax_usd',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='total_cost_brl',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='total_cost_usd',
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfoliotrade'),
        ),
    ]
