# Generated by Django 3.2 on 2022-10-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0047_auto_20221027_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliohistory',
            name='portfolio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='trade',
            field=models.ForeignKey(default=992, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfoliotrade'),
        ),
    ]
