# Generated by Django 3.2 on 2022-10-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0048_auto_20221027_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliohistory',
            name='trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfoliotrade'),
        ),
    ]
