# Generated by Django 3.2 on 2022-10-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0049_alter_portfoliohistory_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='ticker',
            field=models.CharField(default='HGLG11', max_length=15),
        ),
    ]
