# Generated by Django 3.2 on 2022-10-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0050_portfoliohistory_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='ticker',
        ),
    ]
