# Generated by Django 3.2 on 2022-10-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0051_remove_portfoliohistory_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='asset',
            field=models.CharField(default='HGLG11', max_length=15),
        ),
    ]
