# Generated by Django 3.2 on 2022-11-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_auto_20221104_1329'),
        ('portfolios', '0052_portfoliohistory_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brokers.broker'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='total_shares',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='portfoliotrade',
            name='tax_brl',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='portfoliotrade',
            name='tax_usd',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
