# Generated by Django 3.2 on 2022-11-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0053_auto_20221107_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='broker',
        ),
    ]
