# Generated by Django 3.2 on 2023-01-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_auto_20221104_1329'),
        ('portfolios', '0054_remove_portfoliohistory_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brokers.broker'),
        ),
    ]
