# Generated by Django 3.2 on 2023-01-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0055_portfoliohistory_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodividend',
            name='category',
            field=models.CharField(choices=[('Ações Brasileiras', 'Ações Brasileiras'), ('Fundos Imobiliários', 'Fundos Imobiliários'), ('ETFs', 'ETFs'), ('Stocks', 'Stocks'), ('REITs', 'REITs'), ('Propriedades', 'Propriedades')], default='Ação', max_length=100),
        ),
    ]
