# Generated by Django 3.2 on 2023-01-31 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20220926_1221'),
        ('portfolios', '0056_alter_portfoliodividend_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category_total_brl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('category_total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
    ]
