# Generated by Django 3.2 on 2023-02-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0057_portfolioevolution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioevolution',
            options={'ordering': ['date'], 'verbose_name': 'Evolução do Patrimonio', 'verbose_name_plural': 'Evolução do Patrimonio'},
        ),
        migrations.AlterModelOptions(
            name='portfoliohistory',
            options={'verbose_name_plural': 'Trade History'},
        ),
        migrations.AlterField(
            model_name='portfolioevolution',
            name='category_total_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolioevolution',
            name='category_total_usd',
            field=models.FloatField(default=0),
        ),
    ]
