# Generated by Django 3.2 on 2023-02-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_tag'),
        ('portfolios', '0058_auto_20230201_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinvestment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='categories.Tag'),
        ),
    ]
