# Generated by Django 3.2 on 2023-06-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_tag'),
        ('portfolios', '0059_portfolioinvestment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodividend',
            name='category',
            field=models.CharField(choices=[('Ações Brasileiras', 'Ações Brasileiras'), ('Fundos Imobiliários', 'Fundos Imobiliários'), ('ETFs', 'ETFs'), ('Stocks', 'Stocks'), ('REITs', 'REITs'), ('Propriedades', 'Propriedades'), ('FII', 'Fundos Imobiliários'), ('FI-Infra', 'Fundos Imobiliários'), ('Ação', 'Ações Brasileiras')], default='Ação', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolioinvestment',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='categories.Tag'),
        ),
    ]
