# Generated by Django 3.2 on 2023-06-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0060_auto_20230609_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinvestment',
            name='desired_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioinvestment',
            name='is_radar',
            field=models.BooleanField(default=False),
        ),
    ]
