# Generated by Django 3.2 on 2023-06-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0062_auto_20230625_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinvestment',
            name='total_cost_brl',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='portfolioinvestment',
            name='total_cost_usd',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='portfolioinvestment',
            name='total_today_brl',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='portfolioinvestment',
            name='total_today_usd',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
