# Generated by Django 3.2 on 2023-06-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0063_auto_20230625_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliotrade',
            name='category',
        ),
    ]
