# Generated by Django 3.2 on 2023-06-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0064_remove_portfoliotrade_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliotrade',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='portfoliotrade',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioHistory',
        ),
        migrations.DeleteModel(
            name='PortfolioTrade',
        ),
    ]
