# Generated by Django 3.2 on 2023-07-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0066_remove_portfolioinvestment_is_radar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioinvestment',
            name='shares_amount',
            field=models.FloatField(default=0),
        ),
    ]
