# Generated by Django 3.2 on 2023-07-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_delete_tag'),
        ('portfolios', '0067_alter_portfolioinvestment_shares_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioevolution',
            name='category',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='portfolioevolution',
            name='portfolio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
    ]
