# Generated by Django 3.2 on 2024-12-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0069_auto_20240128_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodividend',
            name='category',
            field=models.CharField(choices=[('Ações Brasileiras', 'Ações Brasileiras'), ('Fundos Imobiliários', 'Fundos Imobiliários'), ('ETF', 'ETF'), ('Stocks', 'Stocks'), ('REITs', 'REITs'), ('Propriedades', 'Propriedades'), ('FII', 'Fundos Imobiliários'), ('FI-Infra', 'Fundos Imobiliários'), ('Ação', 'Ações Brasileiras'), ('US Equities', 'US Equities')], default='Ação', max_length=100),
        ),
    ]
