# Generated by Django 3.2 on 2022-01-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.DecimalField(decimal_places=18, max_digits=18)),
            ],
            options={
                'verbose_name_plural': '  Assets',
                'ordering': ('-ticker',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': '   Categories',
            },
        ),
        migrations.CreateModel(
            name='Fii',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
                ('setor', models.CharField(max_length=255)),
                ('last_dividend', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_yield', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('six_m_yield', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('twelve_m_yield', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('p_vpa', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'verbose_name_plural': ' Fiis',
            },
            bases=('investments.asset',),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
                ('setor', models.CharField(max_length=255)),
                ('twelve_m_yield', models.DecimalField(decimal_places=2, max_digits=18)),
                ('p_vpa', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'verbose_name_plural': ' Stocks',
            },
            bases=('investments.asset',),
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_per_share_brl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='investments.asset')),
            ],
            options={
                'verbose_name_plural': 'Dividends',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='investments.category'),
        ),
    ]
