# Generated by Django 3.2 on 2022-01-27 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
                ('marketcap', models.DecimalField(decimal_places=2, max_digits=18)),
                ('circulating_supply', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'verbose_name_plural': ' Crytpos',
            },
            bases=('investments.asset',),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
    ]
