# Generated by Django 3.2 on 2021-12-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name_plural': '  Assets'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '   Categories'},
        ),
        migrations.AlterModelOptions(
            name='dividend',
            options={'verbose_name_plural': 'Dividends'},
        ),
        migrations.AlterModelOptions(
            name='fii',
            options={'verbose_name_plural': ' Fiis'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': ' Stocks'},
        ),
    ]
