# Generated by Django 3.2 on 2022-01-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_auto_20220127_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='setor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
