# Generated by Django 3.2 on 2022-01-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
        ('investments', '0003_crypto_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
            ],
            options={
                'verbose_name_plural': ' ETFs',
            },
            bases=('investments.asset',),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
