# Generated by Django 3.2 on 2022-02-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_auto_20220127_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': '   Brokers',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='investments.category'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='setor',
            field=models.CharField(choices=[('1', 'MainNet'), ('2', 'SideChain'), ('3', 'Oracle'), ('4', 'Game')], max_length=255),
        ),
    ]
