# Generated by Django 3.2 on 2022-02-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_auto_20220201_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='broker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to='investments.broker'),
        ),
    ]
