# Generated by Django 3.2 on 2022-02-01 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_auto_20220201_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorFii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': '   Setor Fiis',
            },
        ),
        migrations.RemoveField(
            model_name='fii',
            name='setor',
        ),
        migrations.AddField(
            model_name='fii',
            name='setor_fii',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_fiis', to='investments.setorfii'),
        ),
    ]
