# Generated by Django 3.2 on 2022-02-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_auto_20220201_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
