# Generated by Django 3.2 on 2022-02-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_alter_asset_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': '   Setor Cryptos',
            },
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='setor',
        ),
        migrations.AddField(
            model_name='crypto',
            name='setor_crypto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_cryptos', to='investments.setorcrypto'),
        ),
    ]
