# Generated by Django 3.2 on 2022-02-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_auto_20220202_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
            ],
            options={
                'verbose_name_plural': ' Currencies',
            },
            bases=('investments.asset',),
        ),
        migrations.CreateModel(
            name='FixedIncome',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
            ],
            options={
                'verbose_name_plural': ' RendaFixas',
            },
            bases=('investments.asset',),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='circulating_supply',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='marketcap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='setor_crypto',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_cryptos', to='investments.setorcrypto'),
        ),
    ]
