# Generated by Django 3.2 on 2022-02-02 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_auto_20220202_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedincome',
            name='default_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='investments.currency'),
            preserve_default=False,
        ),
    ]
