# Generated by Django 3.2 on 2022-02-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_alter_asset_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='circulating_supply',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='marketcap',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='value_per_share_brl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fii',
            name='last_dividend',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fii',
            name='last_yield',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fii',
            name='p_vpa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fii',
            name='six_m_yield',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fii',
            name='twelve_m_yield',
            field=models.FloatField(default=0),
        ),
    ]
