# Generated by Django 3.2 on 2022-02-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_auto_20220210_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
            ],
            options={
                'verbose_name_plural': ' Private Assets',
            },
            bases=('investments.asset',),
        ),
    ]
