# Generated by Django 3.2 on 2022-06-09 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_auto_20220426_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentFunds',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
                ('ambima_code', models.CharField(max_length=255, unique=True)),
                ('twelve_m_profit', models.FloatField(default=0)),
                ('liquidity', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': '    Investment Funds',
            },
            bases=('investments.asset',),
        ),
    ]
