# Generated by Django 3.2 on 2022-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0017_investmentfunds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedincome',
            name='default_currency',
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='credit',
            field=models.CharField(choices=[('Bancario', 'Bancario'), ('Soberano', 'Soberano'), ('Privado', 'Privado')], default='Bancario', max_length=255),
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='credit_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='deadline',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='indexer',
            field=models.CharField(choices=[('IPCA', 'IPCA'), ('CDI', 'CDI'), ('Selic', 'Selic'), ('IGPM', 'IGPM')], default='IPCA', max_length=255),
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='interest_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='is_Ir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='issuer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fixedincome',
            name='kind',
            field=models.CharField(choices=[('Pre-Fixado', 'Pre-Fixado'), ('Pos-Fixado', 'Pos-Fixado'), ('Misto', 'Misto')], default='Pre-Fixado', max_length=255),
        ),
    ]
