# Generated by Django 3.2 on 2022-06-22 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_setorbrstocks'),
        ('investments', '0019_auto_20220609_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='BrStocks',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
                ('twelve_m_yield', models.FloatField(default=0)),
                ('ev_ebit', models.FloatField(default=0)),
                ('roic', models.FloatField(default=0)),
                ('pl', models.FloatField(default=0)),
                ('roe', models.FloatField(default=0)),
                ('p_vpa', models.FloatField(default=0)),
                ('setor_br_stocks', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_br_stocks', to='categories.setorbrstocks')),
            ],
            options={
                'verbose_name_plural': '   Brazilian Stocks',
            },
            bases=('investments.asset',),
        ),
    ]
