# Generated by Django 3.2 on 2022-06-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0020_auto_20220622_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='brstocks',
            name='ranking',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fii',
            name='ranking',
            field=models.FloatField(default=0),
        ),
    ]
