# Generated by Django 3.2 on 2022-09-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_subcategory'),
        ('investments', '0022_brstocks_ranking_all'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brstocks',
            options={'verbose_name_plural': '   Ações Brasileiras'},
        ),
        migrations.AlterModelOptions(
            name='fii',
            options={'verbose_name_plural': '  Fundos Imobiliários'},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name_plural': '   Ações Internacionais'},
        ),
        migrations.AddField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.subcategory'),
        ),
    ]
