# Generated by Django 3.2 on 2022-09-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0023_auto_20220925_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brstocks',
            options={'verbose_name_plural': 'Ações Brasileiras'},
        ),
        migrations.AlterModelOptions(
            name='crypto',
            options={'verbose_name_plural': 'Criptomoedas'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Moedas Estrangeiras'},
        ),
        migrations.AlterModelOptions(
            name='fii',
            options={'verbose_name_plural': 'Fundos Imobiliários'},
        ),
        migrations.AlterModelOptions(
            name='fixedincome',
            options={'verbose_name_plural': 'Renda Fixa'},
        ),
        migrations.AlterModelOptions(
            name='investmentfunds',
            options={'verbose_name_plural': 'Fundos de Investimentos'},
        ),
        migrations.AlterModelOptions(
            name='privateasset',
            options={'verbose_name_plural': 'Ativos Patrimoniais'},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name_plural': 'Ações Internacionais'},
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='setor_crypto',
        ),
    ]
