# Generated by Django 3.2 on 2022-09-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_subcategory'),
        ('investments', '0024_auto_20220925_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brstocks',
            name='setor_br_stocks',
        ),
        migrations.AlterField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.subcategory'),
        ),
    ]
