# Generated by Django 3.2 on 2022-09-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0025_auto_20220925_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('-ticker',), 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='brstocks',
            options={'verbose_name_plural': ' Ações Brasileiras'},
        ),
        migrations.AlterModelOptions(
            name='crypto',
            options={'verbose_name_plural': 'Internacional / Criptomoedas'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Internacional / Moedas'},
        ),
        migrations.AlterModelOptions(
            name='fii',
            options={'verbose_name_plural': ' Fundos Imobiliários'},
        ),
        migrations.AlterModelOptions(
            name='fixedincome',
            options={'verbose_name_plural': ' Renda Fixa'},
        ),
        migrations.AlterModelOptions(
            name='investmentfunds',
            options={'verbose_name_plural': ' Fundos de Investimentos'},
        ),
        migrations.AlterModelOptions(
            name='privateasset',
            options={'verbose_name_plural': 'Patrimônio Particular'},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name_plural': 'Internacional / Stocks'},
        ),
        migrations.RemoveField(
            model_name='fii',
            name='setor_fii',
        ),
    ]
