# Generated by Django 3.2 on 2022-09-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0026_auto_20220925_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brstocks',
            name='p_vpa',
        ),
        migrations.RemoveField(
            model_name='brstocks',
            name='twelve_m_yield',
        ),
        migrations.RemoveField(
            model_name='fii',
            name='p_vpa',
        ),
        migrations.RemoveField(
            model_name='fii',
            name='twelve_m_yield',
        ),
        migrations.AddField(
            model_name='asset',
            name='p_vpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='twelve_m_dividend',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='twelve_m_yield',
            field=models.FloatField(default=0),
        ),
    ]
