# Generated by Django 3.2 on 2022-09-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0027_auto_20220925_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reit',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
                ('is_dividend_aristocrat', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Internacional / REIT',
            },
            bases=('investments.asset',),
        ),
        migrations.AddField(
            model_name='asset',
            name='bottom_52w',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='dividend_frequency',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='top_52w',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='is_dividend_aristocrat',
            field=models.BooleanField(default=False),
        ),
    ]
