# Generated by Django 3.2 on 2022-09-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0028_auto_20220926_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='bottom_52w',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='top_52w',
            field=models.FloatField(default=0),
        ),
    ]
