# Generated by Django 3.2 on 2022-09-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0029_auto_20220926_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='dividend_frequency',
            field=models.FloatField(default=4),
        ),
    ]
