# Generated by Django 3.2 on 2022-09-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0030_alter_asset_dividend_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='bottom_52w',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='dividend_frequency',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='top_52w',
        ),
    ]
