# Generated by Django 3.2 on 2022-09-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0032_auto_20220926_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_usd',
            field=models.FloatField(default=0),
        ),
    ]
