# Generated by Django 3.2 on 2022-10-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0033_auto_20220929_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
    ]
