# Generated by Django 3.2 on 2023-06-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0034_remove_asset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_radar',
            field=models.BooleanField(default=True),
        ),
    ]
