# Generated by Django 3.2 on 2023-06-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0035_asset_is_radar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brstocks',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='brstocks',
            name='ranking_all',
        ),
        migrations.RemoveField(
            model_name='fii',
            name='ranking',
        ),
        migrations.AddField(
            model_name='asset',
            name='ranking',
            field=models.FloatField(default=0),
        ),
    ]
