# Generated by Django 3.2 on 2023-06-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0036_auto_20230615_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='fii',
            name='assets',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fii',
            name='cap_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fii',
            name='ffo_yield',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fii',
            name='liqudity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fii',
            name='market_cap',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fii',
            name='price_m2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fii',
            name='rent_m2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fii',
            name='vacancy',
            field=models.FloatField(default=0),
        ),
    ]
