# Generated by Django 3.2 on 2023-06-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0037_auto_20230615_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fii',
            old_name='liqudity',
            new_name='liquidity',
        ),
    ]
