# Generated by Django 3.2 on 2023-06-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0039_auto_20230618_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='reit',
            name='ffo_yield',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='ffo_yield',
            field=models.FloatField(default=0),
        ),
    ]
