# Generated by Django 3.2 on 2023-08-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_delete_tag'),
        ('investments', '0048_alter_currencyholding_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.subcategory'),
        ),
    ]
