# Generated by Django 3.2 on 2023-09-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0049_auto_20230810_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etf',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
                ('is_dividend_aristocrat', models.BooleanField(default=False)),
                ('der', models.FloatField(default=0)),
                ('ffo', models.FloatField(default=0)),
                ('p_ffo', models.FloatField(default=0)),
                ('earnings_yield', models.FloatField(default=0)),
                ('roic', models.FloatField(default=0)),
                ('ffo_yield', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Internacional / ETF',
            },
            bases=('investments.asset',),
        ),
    ]
