# Generated by Django 3.2 on 2024-06-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_geolocation'),
        ('investments', '0050_etf'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='geolocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.geolocation'),
        ),
    ]
