# Generated by Django 3.2 on 2024-06-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0051_asset_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='geolocation',
        ),
    ]
