# Generated by Django 3.2 on 2024-06-18 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_geolocation'),
        ('investments', '0051_asset_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='geolocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='geolocations', to='categories.geolocation'),
        ),
    ]
