# Generated by Django 3.2 on 2024-12-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0052_alter_asset_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityProvider',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.asset')),
                ('pool_address', models.CharField(default='', max_length=255)),
                ('position_address', models.CharField(default='', max_length=255)),
                ('whirlpool', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Provedores de Liquidez',
            },
            bases=('investments.asset',),
        ),
    ]
