# Generated by Django 3.2 on 2024-06-24 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0052_alter_asset_geolocation'),
        ('portfolios', '0069_auto_20240128_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], default='CALL', max_length=4)),
                ('price_brl', models.FloatField()),
                ('strike_price', models.FloatField()),
                ('option_ticker', models.CharField(max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.asset')),
                ('expiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.expiration')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLD', 'Sold'), ('BOUGHT', 'Bought'), ('CLOSED', 'Closed'), ('EXERCISED', 'Exercised'), ('EXPIRED', 'Expired')], default='SOLD', max_length=10)),
                ('quantity', models.FloatField()),
                ('price_brl', models.FloatField(help_text='Premium received per option.')),
                ('total_brl', models.FloatField(help_text='Total premium received, calculated as price_brl * quantity.')),
                ('collateral_total_price_brl', models.FloatField(blank=True, editable=False, null=True)),
                ('buyback_price', models.FloatField(default=0)),
                ('total_profit_brl', models.FloatField(default=0, editable=False)),
                ('profit_percentage', models.FloatField(default=0, editable=False)),
                ('exercise_price_brl', models.FloatField(default=0, editable=False)),
                ('collateral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolios.portfolioinvestment')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.option')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_options', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='options.option')),
            ],
            bases=('options.option',),
        ),
        migrations.CreateModel(
            name='PortfolioCalls',
            fields=[
                ('portfoliooption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='options.portfoliooption')),
            ],
            bases=('options.portfoliooption',),
        ),
        migrations.CreateModel(
            name='PortfolioPuts',
            fields=[
                ('portfoliooption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='options.portfoliooption')),
            ],
            bases=('options.portfoliooption',),
        ),
        migrations.CreateModel(
            name='Put',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='options.option')),
            ],
            bases=('options.option',),
        ),
    ]
