# Generated by Django 3.2 on 2024-06-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='has_market_maker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='total_brl',
            field=models.FloatField(editable=False),
        ),
    ]
