# Generated by Django 3.2 on 2024-07-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_auto_20240625_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'verbose_name': 'Call Option', 'verbose_name_plural': 'Call Options'},
        ),
        migrations.AlterModelOptions(
            name='expiration',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='portfoliocalls',
            options={'verbose_name': 'Portfolio Call Option', 'verbose_name_plural': 'Portfolio Call Options'},
        ),
        migrations.AlterModelOptions(
            name='portfolioputs',
            options={'verbose_name': 'Portfolio Put Option', 'verbose_name_plural': 'Portfolio Put Options'},
        ),
        migrations.AlterModelOptions(
            name='put',
            options={'verbose_name': 'Put Option', 'verbose_name_plural': 'Put Options'},
        ),
    ]
