# Generated by Django 3.2 on 2023-07-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0068_auto_20230705_2026'),
        ('cashflow', '0022_delete_transactionshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('dividend_receive', 'Dividend Receive'), ('dividend_pay', 'Dividend Pay'), ('subscription', 'Subscription'), ('redemption', 'Redemption'), ('asset_valuation', 'Asset Valuation')], max_length=50)),
                ('new_total_quotas', models.FloatField()),
                ('new_quota_price_brl', models.FloatField()),
                ('new_quota_price_usd', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('currencytransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashflow.currencytransaction')),
            ],
            bases=('cashflow.currencytransaction',),
        ),
        migrations.CreateModel(
            name='AssetValuationEvent',
            fields=[
                ('quotaevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equity.quotaevent')),
            ],
            bases=('equity.quotaevent',),
        ),
        migrations.CreateModel(
            name='DividendPayEvent',
            fields=[
                ('quotaevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equity.quotaevent')),
                ('total_dividends_brl', models.FloatField()),
                ('total_dividends_usd', models.FloatField()),
            ],
            bases=('equity.quotaevent',),
        ),
        migrations.CreateModel(
            name='DividendReceiveEvent',
            fields=[
                ('quotaevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equity.quotaevent')),
                ('total_dividends_brl', models.FloatField()),
                ('total_dividends_usd', models.FloatField()),
            ],
            bases=('equity.quotaevent',),
        ),
        migrations.CreateModel(
            name='RedemptionEvent',
            fields=[
                ('quotaevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equity.quotaevent')),
                ('sold_quotas', models.FloatField()),
            ],
            bases=('equity.quotaevent',),
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('quotaevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equity.quotaevent')),
                ('paid_amount_brl', models.FloatField()),
                ('paid_amount_usd', models.FloatField()),
            ],
            bases=('equity.quotaevent',),
        ),
        migrations.CreateModel(
            name='QuotaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quotas', models.FloatField()),
                ('quota_price_brl', models.FloatField()),
                ('quota_price_usd', models.FloatField()),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='QuotaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_quotas', models.FloatField()),
                ('quota_price_brl', models.FloatField()),
                ('quota_price_usd', models.FloatField()),
                ('event_type', models.CharField(max_length=50)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
    ]
