# Generated by Django 3.2 on 2023-07-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0022_delete_transactionshistory'),
        ('equity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionTransaction',
        ),
    ]
