# Generated by Django 3.2 on 2023-07-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0002_delete_subscriptiontransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividendpayevent',
            name='quotaevent_ptr',
        ),
        migrations.RemoveField(
            model_name='dividendreceiveevent',
            name='quotaevent_ptr',
        ),
        migrations.RemoveField(
            model_name='quotaevent',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='quotastate',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='redemptionevent',
            name='quotaevent_ptr',
        ),
        migrations.RemoveField(
            model_name='subscriptionevent',
            name='quotaevent_ptr',
        ),
        migrations.DeleteModel(
            name='AssetValuationEvent',
        ),
        migrations.DeleteModel(
            name='DividendPayEvent',
        ),
        migrations.DeleteModel(
            name='DividendReceiveEvent',
        ),
        migrations.DeleteModel(
            name='QuotaEvent',
        ),
        migrations.DeleteModel(
            name='QuotaState',
        ),
        migrations.DeleteModel(
            name='RedemptionEvent',
        ),
        migrations.DeleteModel(
            name='SubscriptionEvent',
        ),
    ]
