# Generated by Django 3.2 on 2023-07-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0068_auto_20230705_2026'),
        ('equity', '0004_quotastate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('dividend_receive', 'Dividend Receive'), ('dividend_pay', 'Dividend Pay'), ('subscription', 'Subscription'), ('redemption', 'Redemption'), ('asset_valuation', 'Asset Valuation')], max_length=50)),
                ('new_total_quotas', models.FloatField()),
                ('new_quota_price_brl', models.FloatField()),
                ('new_quota_price_usd', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
    ]
