# Generated by Django 3.2 on 2023-07-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0005_quotaevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('quotaevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equity.quotaevent')),
                ('paid_amount_brl', models.FloatField()),
                ('paid_amount_usd', models.FloatField()),
            ],
            bases=('equity.quotaevent',),
        ),
    ]
