# Generated by Django 3.2 on 2023-07-16 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0068_auto_20230705_2026'),
        ('equity', '0007_auto_20230716_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotahistory',
            name='percentage_change',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='portfolio',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='quota_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='quota_price_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='quota_price_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='total_today_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='total_today_usd',
            field=models.FloatField(default=0),
        ),
    ]
