# Generated by Django 3.2 on 2023-07-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0008_auto_20230716_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotahistory',
            name='percentage_change',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='quota_amount',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='quota_price_brl',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='quota_price_usd',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='total_today_brl',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='total_today_usd',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
