# Generated by Django 3.2 on 2023-07-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0025_delete_subscriptionevent'),
        ('equity', '0010_quotahistory_currency_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('currencytransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashflow.currencytransaction')),
            ],
            bases=('cashflow.currencytransaction',),
        ),
    ]
