# Generated by Django 3.2 on 2023-07-18 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0013_auto_20230718_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliohistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
