# Generated by Django 3.2 on 2023-07-19 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0014_alter_portfoliohistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotahistory',
            name='currency_transaction',
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='event_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('sell', 'sell'), ('Valuation', 'Valuation')], default='deposit', max_length=20),
        ),
        migrations.DeleteModel(
            name='PortfolioHistory',
        ),
    ]
