# Generated by Django 3.2 on 2023-07-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0015_auto_20230719_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotahistory',
            name='event_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw'), ('Valuation', 'Valuation')], default='deposit', max_length=20),
        ),
    ]
