# Generated by Django 3.2 on 2023-07-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0016_alter_quotahistory_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotahistory',
            name='event_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw'), ('valuation', 'valuation')], default='deposit', max_length=20),
        ),
    ]
