# Generated by Django 3.2 on 2023-07-19 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0026_alter_currencytransaction_transaction_type'),
        ('equity', '0017_alter_quotahistory_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionEvent',
            fields=[
                ('currencytransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashflow.currencytransaction')),
            ],
            bases=('cashflow.currencytransaction',),
        ),
    ]
