# Generated by Django 3.2 on 2023-07-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0020_portfoliohistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='value_brl',
            new_name='total_brl',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='value_usd',
            new_name='total_usd',
        ),
    ]
