# Generated by Django 3.2 on 2023-07-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0028_auto_20230721_1527'),
        ('portfolios', '0068_auto_20230705_2026'),
        ('brokers', '0011_delete_currency'),
        ('investments', '0048_alter_currencyholding_currency'),
        ('equity', '0024_auto_20230723_1756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestEvent',
            new_name='InvestBrEvent',
        ),
    ]
