# Generated by Django 3.2 on 2023-07-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0068_auto_20230705_2026'),
        ('equity', '0027_rename_assetvaluationevent_valuationevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioHistory',
            new_name='PortfolioTotalHistory',
        ),
        migrations.AlterModelOptions(
            name='dividendreceiveevent',
            options={'verbose_name': 'Recebimento de Dividendos', 'verbose_name_plural': '  Recebimento de Dividendos'},
        ),
        migrations.AlterModelOptions(
            name='investbrevent',
            options={'verbose_name_plural': ' Comprar no Brasil'},
        ),
        migrations.AlterModelOptions(
            name='portfoliototalhistory',
            options={'verbose_name_plural': 'Histórico dos Portfolios - Total'},
        ),
        migrations.AlterModelOptions(
            name='quotahistory',
            options={'ordering': ['-date'], 'verbose_name_plural': ' Historico de Cotas'},
        ),
        migrations.AlterModelOptions(
            name='redemptionevent',
            options={'verbose_name': 'Resgate', 'verbose_name_plural': '  Resgates - Diminuição de Cotas'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionevent',
            options={'verbose_name': 'Subscrição', 'verbose_name_plural': '    Subscrições - Aumento de Cotas'},
        ),
        migrations.AlterModelOptions(
            name='valuationevent',
            options={'verbose_name': 'Valuation do Portfolio', 'verbose_name_plural': 'Valuation dos Portfolios'},
        ),
    ]
