# Generated by Django 3.2 on 2023-07-26 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0028_auto_20230721_1527'),
        ('equity', '0028_auto_20230724_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayEvent',
            fields=[
                ('currencytransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashflow.currencytransaction')),
            ],
            options={
                'verbose_name': 'Pagamento de Dividendos',
                'verbose_name_plural': ' Pagamento de Dividendos',
            },
            bases=('cashflow.currencytransaction',),
        ),
        migrations.AlterModelOptions(
            name='dividendpayevent',
            options={'verbose_name': 'Pagamento de Dividendos', 'verbose_name_plural': ' Pagamento de Dividendos'},
        ),
        migrations.AlterModelOptions(
            name='investbrevent',
            options={'verbose_name_plural': '  Comprar / Investir no Brasil'},
        ),
        migrations.AlterModelOptions(
            name='quotahistory',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Historico dos Portfolios - Cotas'},
        ),
        migrations.AlterModelOptions(
            name='redemptionevent',
            options={'verbose_name': 'Resgate', 'verbose_name_plural': '   Resgates - Diminuição de Cotas'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionevent',
            options={'verbose_name': 'Subscrição', 'verbose_name_plural': '     Subscrições - Aumento de Cotas'},
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='quotahistory',
            name='event_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw'), ('valuation', 'valuation'), ('dividend receive', 'dividend receive'), ('dividend payment', 'dividend payment'), ('invest br', 'invest br'), ('tax payment', 'tax payment')], default='deposit', max_length=20),
        ),
    ]
