# Generated by Django 3.2 on 2023-08-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0048_alter_currencyholding_currency'),
        ('cashflow', '0028_auto_20230721_1527'),
        ('equity', '0029_auto_20230726_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxpayevent',
            options={'verbose_name': 'Pagamento de Impostos', 'verbose_name_plural': ' Pagamento de Impostos'},
        ),
        migrations.CreateModel(
            name='DivestBrEvent',
            fields=[
                ('currencytransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashflow.currencytransaction')),
                ('trade_amount', models.FloatField(default=0)),
                ('asset_price_brl', models.FloatField(default=0)),
                ('asset', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investments.asset')),
            ],
            options={
                'verbose_name_plural': '  Vender / Desinvestir no Brasil',
            },
            bases=('cashflow.currencytransaction',),
        ),
    ]
