# Generated by Django 3.2 on 2023-09-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0028_auto_20230721_1527'),
        ('investments', '0050_etf'),
        ('equity', '0030_auto_20230810_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotahistory',
            name='event_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw'), ('valuation', 'valuation'), ('dividend receive', 'dividend receive'), ('dividend payment', 'dividend payment'), ('invest br', 'invest br'), ('divest br', 'divest br'), ('tax payment', 'tax payment')], default='deposit', max_length=20),
        ),
        migrations.CreateModel(
            name='InvestUsEvent',
            fields=[
                ('currencytransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashflow.currencytransaction')),
                ('trade_amount', models.FloatField(default=0)),
                ('asset_price_usd', models.FloatField(default=0)),
                ('asset', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investments.asset')),
            ],
            bases=('cashflow.currencytransaction',),
        ),
        migrations.CreateModel(
            name='DivestUsEvent',
            fields=[
                ('currencytransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashflow.currencytransaction')),
                ('trade_amount', models.FloatField(default=0)),
                ('asset_price_usd', models.FloatField(default=0)),
                ('asset', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investments.asset')),
            ],
            bases=('cashflow.currencytransaction',),
        ),
    ]
