# Generated by Django 3.2 on 2024-06-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_geolocation'),
        ('portfolios', '0069_auto_20240128_1457'),
        ('equity', '0032_alter_quotahistory_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHistoryByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_brl', models.FloatField()),
                ('total_usd', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Histórico de Portfólios por Categoria',
                'ordering': ('-date', 'category'),
            },
        ),
    ]
