# Generated by Django 3.2 on 2024-06-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0011_delete_currency'),
        ('equity', '0033_portfoliohistorybycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='divestbrevent',
            name='to_broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brokers.broker'),
        ),
    ]
