# Generated by Django 3.2 on 2024-07-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0069_auto_20240128_1457'),
        ('brokers', '0011_delete_currency'),
        ('cashflow', '0028_auto_20230721_1527'),
        ('equity', '0037_alter_dividendpayevent_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DividendPayEvent',
            new_name='DividendDistributionEvent',
        ),
        migrations.AlterModelOptions(
            name='divestbrevent',
            options={'verbose_name_plural': '   Vender / Desinvestir no Brasil'},
        ),
        migrations.AlterModelOptions(
            name='divestusevent',
            options={'verbose_name_plural': '   Vender / Desinvestir no Exterior'},
        ),
        migrations.AlterModelOptions(
            name='investbrevent',
            options={'verbose_name_plural': '   Comprar / Investir no Brasil'},
        ),
        migrations.AlterModelOptions(
            name='investusevent',
            options={'verbose_name_plural': '   Comprar / Investir no Exterior'},
        ),
        migrations.AlterModelOptions(
            name='quotahistory',
            options={'ordering': ['-date'], 'verbose_name_plural': '       Quotas dos Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='redemptionevent',
            options={'verbose_name': 'Resgate', 'verbose_name_plural': '     Resgates - Diminuição de Cotas'},
        ),
        migrations.AlterModelOptions(
            name='sendmoneyevent',
            options={'verbose_name': 'Remessa', 'verbose_name_plural': '    Remessas Internacionais'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionevent',
            options={'verbose_name': 'Subscrição', 'verbose_name_plural': '      Subscrições - Aumento de Cotas'},
        ),
        migrations.AlterModelOptions(
            name='taxpayevent',
            options={'verbose_name': 'Pagamento de Impostos', 'verbose_name_plural': '  Pagamento de Impostos'},
        ),
        migrations.AlterModelOptions(
            name='valuationevent',
            options={'verbose_name': 'Valuation do Portfolio', 'verbose_name_plural': '       Valuation dos Portfolios'},
        ),
    ]
