# Generated by Django 3.2 on 2023-07-13 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0048_alter_currencyholding_currency'),
        ('portfolios', '0068_auto_20230705_2026'),
        ('brokers', '0011_delete_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=50)),
                ('transaction_amount', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_brl', models.FloatField(blank=True, null=True)),
                ('price_usd', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investments.asset')),
                ('broker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brokers.broker')),
                ('portfolio', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
                ('portfolio_investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
            ],
            options={
                'verbose_name': ' Compra e Venda de Ativo',
                'verbose_name_plural': ' Compra e Venda de Ativos',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_average_price_brl', models.FloatField()),
                ('share_average_price_usd', models.FloatField()),
                ('total_shares', models.FloatField()),
                ('total_brl', models.FloatField()),
                ('total_usd', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('portfolio_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trade.assettransaction')),
            ],
            options={
                'verbose_name': ' Compra e Venda / Histórico',
                'verbose_name_plural': ' Compras e Vendas / Histórico',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransactionCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_average_price_brl', models.FloatField(default=0)),
                ('share_average_price_usd', models.FloatField(default=0)),
                ('trade_profit_brl', models.FloatField(default=0)),
                ('trade_profit_usd', models.FloatField(default=0)),
                ('total_shares', models.FloatField(default=0)),
                ('total_brl', models.FloatField(default=0)),
                ('total_usd', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.assettransaction')),
                ('portfolio_investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
            ],
            options={
                'verbose_name': ' Compra e Venda / Calculos',
                'verbose_name_plural': ' Compras e Vendas / Calculos',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
