# Generated by Django 3.2 on 2023-07-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0048_alter_currencyholding_currency'),
        ('portfolios', '0068_auto_20230705_2026'),
        ('brokers', '0011_delete_currency'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetTransaction',
            new_name='Trade',
        ),
        migrations.RenameModel(
            old_name='AssetTransactionCalculation',
            new_name='TradeCalculation',
        ),
    ]
