# Generated by Django 3.2 on 2023-07-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0015_alter_portfoliodividend_transaction_history'),
        ('portfolios', '0068_auto_20230705_2026'),
        ('trade', '0002_auto_20230713_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionsHistory',
            new_name='TradeHistory',
        ),
    ]
