# Generated by Django 3.2 on 2023-07-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_rename_transactionshistory_tradehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-trade_date'], 'verbose_name': ' Compra e Venda de Ativo', 'verbose_name_plural': ' Compra e Venda de Ativos'},
        ),
        migrations.AlterModelOptions(
            name='tradecalculation',
            options={'ordering': ['-trade_date'], 'verbose_name': ' Compra e Venda / Calculos', 'verbose_name_plural': ' Compras e Vendas / Calculos'},
        ),
        migrations.AlterModelOptions(
            name='tradehistory',
            options={'ordering': ['-trade_date'], 'verbose_name': ' Compra e Venda / Histórico', 'verbose_name_plural': ' Compras e Vendas / Histórico'},
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='transaction_amount',
            new_name='trade_amount',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='transaction_date',
            new_name='trade_date',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='transaction_type',
            new_name='trade_type',
        ),
        migrations.RenameField(
            model_name='tradecalculation',
            old_name='transaction_date',
            new_name='trade_date',
        ),
        migrations.RenameField(
            model_name='tradehistory',
            old_name='transaction_date',
            new_name='trade_date',
        ),
    ]
