# Generated by Django 3.2 on 2022-04-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0015_privateasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_per_share_brl', models.FloatField()),
                ('record_date', models.DateField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='investments.asset')),
            ],
            options={
                'verbose_name_plural': 'Dividends',
            },
        ),
    ]
