# Generated by Django 3.2 on 2022-09-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividend',
            options={'verbose_name_plural': 'Dividendos por ativo'},
        ),
    ]
