# Generated by Django 3.2 on 2022-10-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0002_alter_dividend_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='value_per_share_usd',
            field=models.FloatField(default=0),
        ),
    ]
