# Generated by Django 3.2 on 2022-10-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0003_dividend_value_per_share_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='group',
            field=models.CharField(choices=[('Dividend', 'Dividend'), ('Dividend Tax', 'Dividend Tax')], default='Dividend', max_length=255),
        ),
    ]
