# Generated by Django 3.2 on 2022-10-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0004_dividend_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='group',
            field=models.CharField(choices=[('Dividend', 'Dividend'), ('DividendTax', 'Dividend Tax')], default='Dividend', max_length=255),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='value_per_share_brl',
            field=models.FloatField(default=0),
        ),
    ]
