# Generated by Django 3.2 on 2023-07-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0005_auto_20221004_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend',
            name='group',
        ),
    ]
