# Generated by Django 3.2 on 2023-07-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0045_currencyholding_currency'),
        ('portfolios', '0068_auto_20230705_2026'),
        ('dividends', '0006_remove_dividend_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='0', max_length=10)),
                ('category', models.CharField(choices=[('Ações Brasileiras', 'Ações Brasileiras'), ('Fundos Imobiliários', 'Fundos Imobiliários'), ('ETFs', 'ETFs'), ('Stocks', 'Stocks'), ('REITs', 'REITs'), ('Propriedades', 'Propriedades'), ('FII', 'Fundos Imobiliários'), ('FI-Infra', 'Fundos Imobiliários'), ('Ação', 'Ações Brasileiras')], default='Ação', max_length=100)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('shares_amount', models.FloatField(default=0)),
                ('value_per_share_brl', models.FloatField(default=0)),
                ('value_per_share_usd', models.FloatField(default=0)),
                ('average_price_brl', models.FloatField(default=0)),
                ('average_price_usd', models.FloatField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.asset')),
                ('portfolio_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
            ],
            options={
                'verbose_name_plural': 'Dividendos por Portfolio',
            },
        ),
    ]
