# Generated by Django 3.2 on 2023-07-06 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0007_portfoliodividend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliodividend',
            name='ticker',
        ),
    ]
