# Generated by Django 3.2 on 2023-07-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0009_portfoliodividend_dividend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='pay_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='record_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliodividend',
            name='pay_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliodividend',
            name='record_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
