# Generated by Django 3.2 on 2023-07-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0045_currencyholding_currency'),
        ('dividends', '0010_auto_20230707_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividend',
            options={'verbose_name_plural': 'Dividendos'},
        ),
        migrations.AlterField(
            model_name='dividend',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='investments.asset'),
        ),
    ]
