# Generated by Django 3.2 on 2023-07-09 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_delete_tag'),
        ('dividends', '0012_remove_portfoliodividend_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodividend',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
