# Generated by Django 3.2 on 2023-07-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0019_auto_20230709_1151'),
        ('dividends', '0013_portfoliodividend_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodividend',
            name='transaction_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashflow.transactionshistory'),
        ),
    ]
