# Generated by Django 3.2 on 2023-07-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0015_alter_portfoliodividend_transaction_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliodividend',
            old_name='transaction_history',
            new_name='trade_history',
        ),
    ]
