# Generated by Django 3.2 on 2023-07-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0016_rename_transaction_history_portfoliodividend_trade_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendBr',
            fields=[
                ('dividend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dividends.dividend')),
            ],
            options={
                'verbose_name_plural': 'Dividendos BR',
            },
            bases=('dividends.dividend',),
        ),
    ]
