# Generated by Django 3.2 on 2024-07-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0018_dividendus'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='currency',
            field=models.CharField(default='BRL', max_length=3),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='currency',
            field=models.CharField(default='BRL', max_length=3),
        ),
    ]
