# Generated by Django 3.2 on 2024-07-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0069_auto_20240128_1457'),
        ('dividends', '0019_auto_20240702_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliodividend',
            options={},
        ),
        migrations.CreateModel(
            name='AccumulatedDividends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('accumulated_dividends_brl', models.FloatField(default=0)),
                ('accumulated_dividends_usd', models.FloatField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Dividendos por Portfolio',
            },
        ),
    ]
