# Generated by Django 3.2 on 2024-07-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0020_auto_20240704_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodividend',
            name='total_dividend_brl',
            field=models.FloatField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='portfoliodividend',
            name='total_dividend_usd',
            field=models.FloatField(blank=True, default=0, editable=False, null=True),
        ),
    ]
