# Generated by Django 3.2 on 2023-06-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0007_tag'),
        ('portfolios', '0061_auto_20230620_1427'),
        ('investments', '0043_asset_ideal_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('portfolio_total_value', models.FloatField(default=0.0, editable=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='RadarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideal_category_percentage', models.FloatField(default=0.0)),
                ('category_percentage_on_portfolio', models.FloatField(default=0.0, editable=False)),
                ('category_total_value', models.FloatField(default=0.0, editable=False)),
                ('delta_ideal_actual_percentage', models.FloatField(default=0.0, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radar.radar')),
            ],
            options={
                'unique_together': {('radar', 'category')},
            },
        ),
        migrations.CreateModel(
            name='RadarAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideal_asset_percentage_on_category', models.FloatField(default=0.0)),
                ('ideal_asset_percentage_on_portfolio', models.FloatField(default=0.0)),
                ('portfolio_investment_total_value', models.FloatField(default=0.0, editable=False)),
                ('portfolio_investment_percentage_on_category', models.FloatField(default=0.0, editable=False)),
                ('portfolio_investment_percentage_on_portfolio', models.FloatField(default=0.0, editable=False)),
                ('delta_ideal_actual_percentage_on_category', models.FloatField(default=0.0, editable=False)),
                ('delta_ideal_actual_percentage_on_portfolio', models.FloatField(default=0.0, editable=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.asset')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radar.radar')),
            ],
            options={
                'unique_together': {('radar', 'asset')},
            },
        ),
    ]
