# Generated by Django 3.2 on 2023-06-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0003_auto_20230624_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radarasset',
            name='ideal_asset_percentage_on_portfolio',
        ),
        migrations.AlterField(
            model_name='radarasset',
            name='radar',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='radar.radar'),
        ),
    ]
