# Generated by Django 3.2 on 2023-06-28 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0005_alter_radarasset_radar_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radarasset',
            name='radar_category',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='radar.radarcategory'),
        ),
    ]
