# Generated by Django 3.2 on 2023-07-15 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0006_alter_radarasset_radar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='radarasset',
            name='ideal_category_percentage',
            field=models.FloatField(default=0.1, editable=False),
        ),
        migrations.AlterField(
            model_name='radarasset',
            name='radar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radar.radar'),
        ),
        migrations.AlterField(
            model_name='radarasset',
            name='radar_category',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='radar.radarcategory'),
        ),
    ]
