# Generated by Django 3.2 on 2023-07-06 00:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0068_auto_20230705_2026'),
        ('brokers', '0007_broker_main_currency'),
        ('investments', '0045_currencyholding_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='deposit', max_length=50)),
                ('transaction_amount', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_brl', models.FloatField(blank=True, null=True)),
                ('price_usd', models.FloatField(blank=True, null=True)),
                ('broker', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='brokers.broker')),
                ('portfolio', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
                ('portfolio_investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
            ],
            options={
                'verbose_name_plural': 'Depósitos e Saques',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='InternationalCurrencyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_transfer_amount', models.FloatField(default=0)),
                ('to_transfer_amount', models.FloatField(default=0, editable=False)),
                ('transfer_fee', models.FloatField(default=0)),
                ('exchange_rate', models.FloatField(default=0)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('from_broker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='intl_transfer_from', to='brokers.broker')),
                ('from_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_intl_transfers', to='cashflow.currencytransaction')),
                ('portfolio', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
                ('to_broker', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='intl_transfer_to', to='brokers.broker')),
                ('to_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_intl_transfers', to='cashflow.currencytransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.broker')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.broker')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.FloatField()),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('from_broker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='brokers.broker')),
                ('from_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_transfers', to='cashflow.currencytransaction')),
                ('portfolio', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
                ('to_broker', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='brokers.broker')),
                ('to_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_transfers', to='cashflow.currencytransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyAveragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_average_price_brl', models.FloatField(default=0)),
                ('share_average_price_usd', models.FloatField(default=0)),
                ('portfolio_investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=50)),
                ('transaction_amount', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_brl', models.FloatField(blank=True, null=True)),
                ('price_usd', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investments.asset')),
                ('broker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brokers.broker')),
                ('portfolio', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
                ('portfolio_investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAveragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_average_price_brl', models.FloatField(default=0)),
                ('share_average_price_usd', models.FloatField(default=0)),
                ('trade_profit_brl', models.FloatField(default=0)),
                ('trade_profit_usd', models.FloatField(default=0)),
                ('portfolio_investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
            ],
        ),
    ]
