# Generated by Django 3.2 on 2023-07-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='income',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
