# Generated by Django 3.2 on 2023-07-01 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0045_currencyholding_currency'),
        ('brokers', '0007_broker_main_currency'),
        ('portfolios', '0066_remove_portfolioinvestment_is_radar'),
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalCurrencyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount_in_source_currency', models.FloatField()),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('transfer_fee', models.FloatField()),
                ('exchange_rate', models.FloatField()),
                ('from_portfolio_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international_transfer_from', to='portfolios.portfolioinvestment')),
                ('to_portfolio_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international_transfer_to', to='portfolios.portfolioinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.FloatField()),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('transfer_fee', models.FloatField()),
                ('from_portfolio_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='portfolios.portfolioinvestment')),
                ('to_portfolio_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='portfolios.portfolioinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=50)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.broker')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.currency')),
                ('portfolio_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyAveragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_average_price_brl', models.FloatField(default=0)),
                ('share_average_price_usd', models.FloatField(default=0)),
                ('portfolio_investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=50)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('asset_price_brl', models.FloatField()),
                ('asset_price_usd', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.asset')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.broker')),
                ('portfolio_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_transactions', to='portfolios.portfolioinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAveragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_average_price_brl', models.FloatField(default=0)),
                ('share_average_price_usd', models.FloatField(default=0)),
                ('portfolio_investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
            ],
        ),
    ]
