# Generated by Django 3.2 on 2023-07-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0007_broker_main_currency'),
        ('portfolios', '0066_remove_portfolioinvestment_is_radar'),
        ('cashflow', '0002_assetaverageprice_assettransaction_currencyaverageprice_currencytransaction_currencytransfer_interna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencytransaction',
            name='currency',
        ),
        migrations.AddField(
            model_name='currencytransaction',
            name='portfolio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
        migrations.AlterField(
            model_name='currencytransaction',
            name='broker',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='brokers.broker'),
        ),
        migrations.AlterField(
            model_name='currencytransaction',
            name='portfolio_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment'),
        ),
    ]
