# Generated by Django 3.2 on 2023-07-03 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0067_alter_portfolioinvestment_shares_amount'),
        ('cashflow', '0003_auto_20230702_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencytransaction',
            name='price_brl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencytransaction',
            name='price_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currencytransaction',
            name='portfolio',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
        migrations.AlterField(
            model_name='currencytransaction',
            name='transaction_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='currencytransaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='currencytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='deposit', max_length=50),
        ),
    ]
