# Generated by Django 3.2 on 2023-07-03 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0045_currencyholding_currency'),
        ('brokers', '0007_broker_main_currency'),
        ('portfolios', '0067_alter_portfolioinvestment_shares_amount'),
        ('cashflow', '0004_auto_20230703_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettransaction',
            name='asset_price_brl',
        ),
        migrations.RemoveField(
            model_name='assettransaction',
            name='asset_price_usd',
        ),
        migrations.AddField(
            model_name='assettransaction',
            name='portfolio',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='assettransaction',
            name='price_brl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettransaction',
            name='price_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investments.asset'),
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brokers.broker'),
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='portfolio_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment'),
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='transaction_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=50),
        ),
    ]
