# Generated by Django 3.2 on 2023-07-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_auto_20230706_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaverageprice',
            name='asset_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashflow.assettransaction'),
        ),
    ]
