# Generated by Django 3.2 on 2023-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_auto_20230703_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaverageprice',
            name='trade_profit_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assetaverageprice',
            name='trade_profit_usd',
            field=models.FloatField(default=0),
        ),
    ]
