# Generated by Django 3.2 on 2023-07-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0007_auto_20230704_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetaverageprice',
            name='cost_brl',
        ),
        migrations.RemoveField(
            model_name='assetaverageprice',
            name='cost_usd',
        ),
    ]
