# Generated by Django 3.2 on 2023-07-06 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0007_auto_20230706_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaverageprice',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
