# Generated by Django 3.2 on 2023-07-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0008_auto_20230704_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaverageprice',
            name='cost_brl',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assetaverageprice',
            name='cost_usd',
            field=models.FloatField(null=True),
        ),
    ]
