# Generated by Django 3.2 on 2023-07-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0008_alter_assetaverageprice_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaverageprice',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
