# Generated by Django 3.2 on 2023-07-05 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0067_alter_portfolioinvestment_shares_amount'),
        ('brokers', '0007_broker_main_currency'),
        ('cashflow', '0009_auto_20230704_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetaverageprice',
            name='cost_brl',
        ),
        migrations.RemoveField(
            model_name='assetaverageprice',
            name='cost_usd',
        ),
        migrations.RemoveField(
            model_name='currencytransfer',
            name='from_portfolio_investment',
        ),
        migrations.RemoveField(
            model_name='currencytransfer',
            name='to_portfolio_investment',
        ),
        migrations.RemoveField(
            model_name='currencytransfer',
            name='transfer_fee',
        ),
        migrations.AddField(
            model_name='currencytransfer',
            name='from_broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='brokers.broker'),
        ),
        migrations.AddField(
            model_name='currencytransfer',
            name='from_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_transfers', to='cashflow.currencytransaction'),
        ),
        migrations.AddField(
            model_name='currencytransfer',
            name='portfolio',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='currencytransfer',
            name='price_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currencytransfer',
            name='price_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currencytransfer',
            name='to_broker',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='brokers.broker'),
        ),
        migrations.AddField(
            model_name='currencytransfer',
            name='to_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_transfers', to='cashflow.currencytransaction'),
        ),
        migrations.AlterField(
            model_name='currencytransfer',
            name='transfer_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
