# Generated by Django 3.2 on 2023-07-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0009_alter_assetaverageprice_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetaverageprice',
            name='transaction_date',
        ),
    ]
