# Generated by Django 3.2 on 2023-07-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0010_auto_20230705_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencytransfer',
            name='price_brl',
        ),
        migrations.RemoveField(
            model_name='currencytransfer',
            name='price_usd',
        ),
    ]
