# Generated by Django 3.2 on 2023-07-06 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0010_remove_assetaverageprice_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaverageprice',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
