# Generated by Django 3.2 on 2023-07-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0068_auto_20230705_2026'),
        ('cashflow', '0011_assetaverageprice_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAverageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_average_price_brl', models.FloatField()),
                ('share_average_price_usd', models.FloatField()),
                ('total_shares', models.FloatField()),
                ('total_brl', models.FloatField()),
                ('total_usd', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('portfolio_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioinvestment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.assettransaction')),
            ],
            options={
                'verbose_name': 'Histórico de Preço Médio do Ativo',
                'verbose_name_plural': 'Históricos de Preço Médio do Ativo',
                'ordering': ['-timestamp'],
            },
        ),
    ]
