# Generated by Django 3.2 on 2023-07-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0068_auto_20230705_2026'),
        ('cashflow', '0012_assetaveragehistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetAverageHistory',
            new_name='TransactionsHistory',
        ),
    ]
