# Generated by Django 3.2 on 2023-07-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0014_auto_20230707_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaverageprice',
            name='last_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashflow.assettransaction'),
        ),
    ]
