# Generated by Django 3.2 on 2023-07-08 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0015_assetaverageprice_last_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaverageprice',
            name='last_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.assettransaction'),
        ),
    ]
