# Generated by Django 3.2 on 2023-07-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0068_auto_20230705_2026'),
        ('cashflow', '0016_alter_assetaverageprice_last_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetAveragePrice',
            new_name='AssetTransactionCalculation',
        ),
    ]
