# Generated by Django 3.2 on 2023-07-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0068_auto_20230705_2026'),
        ('cashflow', '0017_rename_assetaverageprice_assettransactioncalculation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrencyAveragePrice',
            new_name='CurrencyTransactionCalculation',
        ),
    ]
