# Generated by Django 3.2 on 2023-07-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0018_rename_currencyaverageprice_currencytransactioncalculation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettransaction',
            options={'ordering': ['-transaction_date'], 'verbose_name': ' Compra e Venda de Ativo', 'verbose_name_plural': ' Compra e Venda de Ativos'},
        ),
        migrations.AlterModelOptions(
            name='assettransactioncalculation',
            options={'ordering': ['-transaction_date'], 'verbose_name': ' Compra e Venda / Calculos', 'verbose_name_plural': ' Compras e Vendas / Calculos'},
        ),
        migrations.AlterModelOptions(
            name='currencytransaction',
            options={'ordering': ['-transaction_date'], 'verbose_name_plural': '  Depósitos e Saques'},
        ),
        migrations.AlterModelOptions(
            name='transactionshistory',
            options={'ordering': ['-transaction_date'], 'verbose_name': ' Compra e Venda / Histórico', 'verbose_name_plural': ' Compras e Vendas / Histórico'},
        ),
    ]
