# Generated by Django 3.2 on 2023-07-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0019_auto_20230709_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionshistory',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cashflow.assettransaction'),
        ),
    ]
