# Generated by Django 3.2 on 2023-07-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0009_auto_20230716_2115'),
        ('cashflow', '0022_delete_transactionshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('currencytransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashflow.currencytransaction')),
                ('quota_history', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equity.quotahistory')),
            ],
            bases=('cashflow.currencytransaction',),
        ),
    ]
