# Generated by Django 3.2 on 2023-07-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0010_quotahistory_currency_transaction'),
        ('cashflow', '0024_remove_subscriptionevent_quota_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionEvent',
        ),
    ]
