# Generated by Django 3.2 on 2023-07-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0025_delete_subscriptionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw')], default='deposit', max_length=50),
        ),
    ]
