# Generated by Django 3.2 on 2024-07-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0028_auto_20230721_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencytransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
