# Generated by Django 3.2 on 2022-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0026_auto_20220925_1543'),
        ('categories', '0004_auto_20220925_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetorFii',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('-name',), 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
