# Generated by Django 3.2 on 2022-09-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20220925_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Áreas de Atuação'},
        ),
    ]
