# Generated by Django 3.2 on 2023-06-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
