# Generated by Django 3.2 on 2024-05-26 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EHT based', 'Ethereum based')], default='Ethereum based', max_length=50)),
                ('address', models.CharField(max_length=42)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WtreeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('description', models.TextField(blank=True, null=True)),
                ('theme', models.CharField(choices=[('defautTheme', 'Default Theme'), ('lightTheme', 'Light Theme')], default='defaultTheme', max_length=50)),
                ('accepted_cryptos', models.ManyToManyField(blank=True, related_name='profiles', to='blockchains.CryptoBase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallets', models.ManyToManyField(blank=True, related_name='profiles', to='wtree.Wallet')),
            ],
        ),
    ]
