# Generated by Django 3.2 on 2024-05-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('icon_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchains.blockchain')),
            ],
        ),
        migrations.CreateModel(
            name='Native',
            fields=[
                ('cryptobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blockchains.cryptobase')),
            ],
            bases=('blockchains.cryptobase',),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('cryptobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blockchains.cryptobase')),
                ('contract_address', models.CharField(max_length=42)),
                ('decimals', models.IntegerField(default=18)),
            ],
            bases=('blockchains.cryptobase',),
        ),
    ]
