# Generated by Django 3.2 on 2021-12-27 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20211222_0122'),
        ('radars', '0002_auto_20211227_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radars', to='portfolios.portfolio'),
        ),
    ]
