# Generated by Django 3.2 on 2021-12-27 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radars', '0003_alter_radar_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radaritem',
            name='radar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radar_items', to='radars.radar'),
        ),
    ]
