# Generated by Django 3.2 on 2024-01-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsQuest',
            fields=[
                ('quest_key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('mission', models.CharField(max_length=255)),
                ('mission_details', models.TextField()),
                ('reward', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kidprofile')),
            ],
            options={
                'verbose_name_plural': 'KidsQuests',
            },
        ),
    ]
