# Generated by Django 3.2 on 2024-01-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_kidsquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidprofile',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
    ]
