# Generated by Django 3.2 on 2024-02-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_kidprofile_current_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsEarns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('category', models.CharField(choices=[('mesada', 'Mesada'), ('tarefas', 'Tarefas'), ('presente', 'Presente'), ('outros', 'Outros')], max_length=255, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
        migrations.CreateModel(
            name='KidsExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('category', models.CharField(choices=[('doces', 'Doces'), ('comidas', 'Comidas'), ('brinquedos', 'Brinquedos'), ('outros', 'Outros')], max_length=255, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
