# Generated by Django 3.2 on 2024-02-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0005_auto_20240205_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kidsearns',
            options={'verbose_name_plural': 'KidsEarns'},
        ),
        migrations.AlterModelOptions(
            name='kidsexpenses',
            options={'verbose_name_plural': 'KidsExpenses'},
        ),
        migrations.AlterField(
            model_name='kidsearns',
            name='category',
            field=models.CharField(choices=[('aluguel', 'Aluguel'), ('missao', 'Missão'), ('presente', 'Presente'), ('outros', 'Outros')], max_length=255, verbose_name='Categoria'),
        ),
    ]
