# Generated by Django 3.2 on 2024-02-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0007_kidsbuttons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidsbuttons',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kidprofile'),
        ),
    ]
