# Generated by Django 3.2 on 2024-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0009_alter_kidsbuttons_belongs_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidprofile',
            name='currency',
            field=models.CharField(choices=[('BRL', 'R$'), ('USD', '$'), ('EUR', '€')], default='BRL', max_length=3),
        ),
        migrations.AddField(
            model_name='kidprofile',
            name='language',
            field=models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('fr', 'Francês')], default='pt', max_length=2),
        ),
    ]
