# Generated by Django 3.2 on 2024-12-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0010_auto_20241011_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidprofile',
            name='currency',
            field=models.CharField(choices=[('R$', 'R$'), ('U$', 'U$'), ('€', '€')], default='BRL', max_length=3),
        ),
    ]
